tag @a remove duskbladesword
tag @a remove painsword
tag @a remove poofsword
tag @a remove divinesword
tag @a remove divineattack
tag @a remove banishedsword
tag @a remove lovesword
tag @a remove sandsword
tag @a remove darksword
tag @a remove firesword
tag @a remove skysword
tag @a remove lightningsword
tag @a remove maelstrom
tag @a remove hydroblaster
tag @a remove bouldersword
tag @a remove fireattack